### ISSUE TITLE
Audio Issue

### ISSUE THREAD

**Issue by sralse** [WorldGrower/WorldGrower#3]
I have no Audio driver and thus the game can't launch (resulting with this error:)

`java.lang.IllegalArgumentException: Mixer not supported: null
	at javax.sound.sampled.AudioSystem.getMixer(Unknown Source)
	at org.worldgrower.gui.music.SoundOutput.getDefaultSoundOutput(SoundOutput.java:42)
	at org.worldgrower.gui.start.StartScreen.loadDefaultSoundOutput(StartScreen.java:178)
	at org.worldgrower.gui.start.StartScreen.main(StartScreen.java:103)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:62)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:101)
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:16)
`

If it's not too much trouble, I would love to try the game out too, thanks!

**Comment by WorldGrower** [comment]
Hi, thanks for the feedback and clear error message.
I fixed this bug locally, when I disable all my audio devices, the game still works.
I released a new version, 1.2.1, that contains the fix:
[https://github.com/WorldGrower/WorldGrower/releases](https://github.com/WorldGrower/WorldGrower/releases)

**Comment by sralse** [comment]
Has been fixed, thanks!

**Comment by WorldGrower** [comment]
Ok, good to hear.
I'll close the issue.
